### ISSUE TITLE
Inline and reference hyperlinks

### ISSUE THREAD

**Issue by joseluisbolos** [springernature/frontend-playbook#102]
The [README](/springernature/frontend#links) says:

> If you need to reuse a hyperlink, turn it into a reference link. Otherwise, use an inline link.

But we're very inconsistent in the use of these, even in the `README` itself. I would suggest to either:
- Just use reference links everywhere, as it helps with legibility when you're reading the raw Markdown without a viewer, or
- Fix the links everywhere according our policy above

**Comment by hollsk** [comment]
I vote for reference links everywhere

**Comment by hollsk** [comment]
I've now changed my mind because I've noticed over the last couple of days that reference links tend to lead to orphaned references with no counterpart in the text, which is kind of confusing 👎

**Comment by joseluisbolos** [comment]
Addressed in #166.
