### ISSUE TITLE
Should we detail our current graded browser support levels here?

### ISSUE THREAD

**Issue by hollsk** [springernature/frontend-playbook#107]
The information is currently published on the intranet so that people inside the business can see it. Now that the Playbook is open source, perhaps we should think about moving it here instead?

**Comment by andrewmee** [comment]
Yes, it makes sense to document this here.

**Comment by joseluisbolos** [comment]
This has now been done: https://github.com/springernature/frontend-playbook/blob/master/practices/graded-browser-support.md
