### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by hollsk** [springernature/frontend-playbook#110]
The Contributor Covenant is used by over 40,000 open source projects (including Pa11y!)

http://contributor-covenant.org/

**Comment by hollsk** [comment]
I've avoided doing this for months just because of one thing - we need a point of contact for people to privately raise issues (e.g. harassment, abuse, other violations). 

I don't want that point of contact to be me, personally, and I don't think it would be appropriate if it were. The point of contact should be wholly neutral, to avoid situations where people have to report a violation _to_ the individual who actually _committed_ the violation. 

Jude, Danyal has assigned this to you for a decision.

**Comment by jpw** [comment]
This is still being worked-on -- turns out it's not easy!

But we are hopefully in the closing stages of getting this resolved.

**Comment by jpw** [comment]
This got mired in some HR-related admin, IIRC. We may pick this up again in the future.
