### ISSUE TITLE
Graded browser support table slightly out of date

### ISSUE THREAD

**Issue by hollsk** [springernature/frontend-playbook#117]
From Jose in #108 

> This is the current list of C-Grade browsers in our legacy platform (which we've been using as a single source of truth so far):
> 
> Internet Explorer <9
> Safari up to 4.0.x on Windows and OS X
> Safari 2 (any) and Safari 3 (iPhone 1)
> Unknown (User-Agent matches '.* AppleWebKit.Version/[0-2]..')
> Safari 1
> Unknown (User-Agent matches '.*Version/2.2 Firefox/525.13')
> Firefox 0.x and 1
> Opera up to 9.4
> Nokia browser for Symbian 7.3
> Android browser up to 2.x
> Old versions of 'Mozilla compatible' browsers
> Netscape
> 
> In bold the ones that don't match what's on the table. As you can see, there are others that are not on the table at all, I'm not sure what we want to do and if we want to put them there.
> 

I don't think there's much value in adding things like Netscape or Moz compat browsers or anything weird and old to the documentation. They exist in the legacy platform because the legacy platform is also weird and old ;) 

Let's update the C-grade column to use any higher values in Jose's comment.

**Comment by danyalaytekin** [comment]
Jose's bold syntax above was lost - these were:

```
Firefox 0.x and 1
Opera up to 9.4
```

**Comment by hollsk** [comment]
This seems to be complete 👍
