### ISSUE TITLE
F-R-O-N-T-E-N-D

### ISSUE THREAD

**Issue by joseluisbolos** [springernature/frontend-playbook#119]
We seem to be somewhat inconsistent in the usage of frontend with/without a hyphen. We need to correct the ones that are wrong.

![image](https://cloud.githubusercontent.com/assets/1792637/21143712/a6fa9dd2-c13f-11e6-9d92-9d0f42185d3d.png)

**Comment by hollsk** [comment]
The bit in the licence is wrong, the other bits are correct. 

The rules:

- use `front-end` when writing in English about the team, the discipline, or the industry;
- use `frontend` when referring to a piece of software (e.g. "the Shunter frontend"), a repository, or in your code

We should probably also document this in the language guide (with "we do/we don't do" examples)

**Comment by Alicole** [comment]
Only use an adjective in prose, but not as a name of a repo for instance as it's a noun

**Comment by danyalaytekin** [comment]
![image](https://cloud.githubusercontent.com/assets/1315042/21232250/ea2fb714-c2e2-11e6-8b82-953d81ed9087.png)

**Comment by joseluisbolos** [comment]
Fixed by #133
