### ISSUE TITLE
Document our approach(es) to webfont loading

### ISSUE THREAD

**Issue by hollsk** [springernature/frontend-playbook#135]
Summary of our discussion earlier today:

> I think we were agreed on loading them with JS.  There was discussion about non js users not getting the font, but that's ok I think.  Even with the JS approach, there's differences between projects.  We use session storage to set a flag once font has loaded, but link save the entire font as a data-uri in local storage (I think?)

>we do save the entire font as a data-uri then retrieve it from local storage. I actually went through that article that was posted and tested out various options and we found this one to be the best for us. BUT it might not be best for all. We only have one webfont, and it has a limited character set so storing at as a data-uri works fine. not sure how well it would work with multiple fonts

>the way we implement it is slightly different from how it is described in the article (https://www.zachleat.com/web/comprehensive-webfonts/#critical-foft-data-uri) as we don't write it inline

>I actually think it is OK that we use slightly different methods, there is still a lot of common ground and we can probably write up a set of broader guidelines and then detail the individual approaches. 

>not like a document that decrees YOU MUST DO XYZ but more a document that outlines the problems, what we tried, and some recommended options

**Comment by danyalaytekin** [comment]
Are webfonts one place where we can actually say, within Springer Nature at least, that we could achieve a single approach, and that "we should do XYZ”?  

Some other things we do, like our varied CSS approaches, require less prescriptive documentation but maybe our webfonts approach belongs more with commandments like our CTM method and “don’t self-close tags”.

**Comment by joseluisbolos** [comment]
I was wondering about this too. If there's a "best approach" that we can agree on and solves most problems it would be better to try to stick to it, rather than "do whatever you want".

**Comment by jpw** [comment]
Consistency FTW. If some universal best practice does emerge, it's easier to fix in one place than many.

**Comment by nickcall** [comment]
Alex will submit a PR

**Comment by Sreilys** [comment]
What do you think about following this article, meantime we set a "standard" way? 
https://www.html5rocks.com/en/tutorials/webfonts/quick/
What do you think about using WebFont Loader approach?

**Comment by davidpauljunior** [comment]
More investigation needed I think to agree on a "standard" approach.

**Comment by sonniesedge** [comment]
Overview of font projects:

## Basic loaders and font-loading monitors:

- https://github.com/bramstein/fontfaceobserver
- https://github.com/zachleat/fontfaceonload

Both fontfaceobserver and fontfaceonload rely on the dev loading the fonts. They listen for the font being loaded and then make a callback available, where you can do what you want. 

- https://github.com/typekit/webfontloader

Webfontloader loads the font via JS. Can append classes indicating load state. 

## Local storage caching
- https://github.com/jaicab/localFont 
- https://github.com/CrocoDillon/font-store

Neither of these have been updated in a couple of years, but localfont seems reasonably popular?

**Comment by josebolos** [comment]
@benjclark has ~been~ volunteered to do this.
