### ISSUE TITLE
Guidelines on handling cookies on domains

### ISSUE THREAD

**Issue by Alicole** [springernature/frontend-playbook#136]
At Nature.com -- particularly on subject pages, we are currently experiencing cookie overload.

Seems likely cause is the way cookies have been created, so falling back on browser's defaults.

Need to ensure that cookies only created if required, and there is no other way of handling any specific case.

If a cookie is created -- then proper headers are added: expiry dates, domain and url.

**Comment by jpw** [comment]
If we are doing work on this front, can we measure the scale of the problem now please so we can assess the need and measure the benefit of any subsequent gains?

**Comment by joseluisbolos** [comment]
What would be the scope of this? What problem are we trying to fix exactly?

We usually don't set up cookies in the frontend (unless we consider third-party stuff part of our frontend, but we have no control over those).

**Comment by jpw** [comment]
Old but maybe useful https://yuiblog.com/blog/2007/03/01/performance-research-part-3/

There is probably more Y! docu out there as this stuff was a big deal there.  IIRC there was a process whereby teams co-ordinated to stuff what they wanted into cookie values, effectively sharing the cookie.
 
I think there is also stuff in https://hpbn.co/  about getting cookies to fit inside packets & frames of a certain size, if we want to get really hardcore

**Comment by dotcode** [comment]
Closing this. We may want to document something about "how to handle 3rd party cookies" at some point, but only when we've figured out how :)
