### ISSUE TITLE
Accessibility - common concerns

### ISSUE THREAD

**Issue by joseluisbolos** [springernature/frontend-playbook#140]
A while ago, when we added the [Accessibility guide](https://github.com/springernature/frontend-playbook/blob/master/practices/accessibility.md), we discussed the need for a ["Common concerns"](https://github.com/springernature/frontend-playbook/blob/master/practices/accessibility.md#common-concerns) section.

I've just realised we added the section but we left it empty. Any volunteers fancy tackling it, or shall we remove it?

**Comment by hollsk** [comment]
What would differentiate it from https://github.com/springernature/frontend-playbook/blob/master/practices/accessibility-checklist.md ? 

There's an "effective colour contrast" page linked to from that document was originally in the old Nature Wiki. Jude and I had a brief discussion about adding it in when he created the checklist document, and that discussion may be of interest here: https://github.com/springernature/frontend-playbook/pull/63

IMO a 'common concerns' section has potential to become enormous and time-consuming, overwhelming the rest of the content, and that we'd be better served by a list of recommendations for external resources.

**Comment by joseluisbolos** [comment]
Hello,

The "common concerns" section was removed 12 days ago as part of [https://github.com/springernature/frontend-playbook/commit/526381ab86f16d0f3c7aaf11c428915a0a483fd3](https://github.com/springernature/frontend-playbook/commit/526381ab86f16d0f3c7aaf11c428915a0a483fd3).

As usual no one remembered to close this issue 👎

**Comment by hollsk** [comment]
Oh right 😂 

Let's close it now then 👍
