### ISSUE TITLE
Review the "Dependency management tools" section

### ISSUE THREAD

**Issue by josebolos** [springernature/frontend-playbook#143]
We added a section about tools for managing Node.js dependencies to our [Dependency management page](https://github.com/springernature/frontend-playbook/blob/master/practices/dependency-management.md#dependency-management-tools).

Maybe it's not the best place to contain that information and we should have a separate page for tools.

**Comment by danyalaytekin** [comment]
Waiting for a volunteer.

**Comment by hollsk** [comment]
I was looking at the semver page earlier and thinking it would be good to have an entire section for Node that included semver and dep management. Could also contain the resolution to #121 once we do that. 

What say you?

**Comment by joseluisbolos** [comment]
I like it. What would that page include?

* Dep management?
* Tools?
* ...
* Profit?

**Comment by hollsk** [comment]
Yes. Tools and dep management for now. I thought semver too, but jon has just moved the semver page under the git folder, so maybe not 😁 

Could also have a bit about how we manage our NPM stuff (aspirationally, i mean, rather than currently 😂  )

**Comment by joseluisbolos** [comment]
#121 to be addressed as part of this. So we have:

* Dep management
* NPM Publising and namespacing
* Tools

**Comment by josebolos** [comment]
Addressed in #183.
