### ISSUE TITLE
Template linting

### ISSUE THREAD

**Issue by joseluisbolos** [springernature/frontend-playbook#156]
It would be good to clarify somewhere that we enforce linting of templates using for example [dustmite](https://github.com/springernature/dustmite).

This helps us prevent issues like the ones mentioned in [Snyk's blog](https://snyk.io/blog/type-manipulation), as our lint rules ban the `if` helper.

**Comment by andrewmee** [comment]
Dealt with in @moddular's PR https://github.com/springernature/frontend-playbook/pull/157
