### ISSUE TITLE
What's 'Mosaic'?

### ISSUE THREAD

**Issue by josebolos** [springernature/frontend-playbook#164]
https://github.com/springernature/frontend-playbook/blob/master/practices/css/mosaic-css.md

This whole page is written under the assumption that you know what Mosaic is, which no one outside the company probably knows. We should describe it more accurately, so it can also be referenced properly from other documents.

**Comment by jpw** [comment]
New link https://github.com/springernature/frontend-playbook/blob/master/css/mosaic-css.md

**Comment by andrewmee** [comment]
This has been moved into the mosaic wiki
