### ISSUE TITLE
Suggestion to make peer review FED process more inclusive

### ISSUE THREAD

**Issue by Alicole** [springernature/frontend-playbook#177]
It might be sensible to make as small tweak to the wording on the PR playbook docs, on following line in Why section to make it more inclusive to wider dev community, as sometimes not just FEDs change templates and code; from, "Ensure that Front-End Developers within each team are coding to the same guidelines." To: "Ensure that any Developers, within each team, who are changing front-end templates or code are conforming to the same guidelines".

Please see: https://github.com/springernature/frontend-playbook/blob/master/practices/code-review.md

**Comment by jpw** [comment]
Closing for now, keeping an eye on the situation.
