### ISSUE TITLE
Add a "performance" section

### ISSUE THREAD

**Issue by hollsk** [springernature/frontend-playbook#180]
I propose a "performance" section to contain the following existing files:

* advertising
* images
* graded browser support
* progressive enhancement

Is this idea awesome Y/N?

**Comment by jpw** [comment]
Is this idea awesome Y/~~N~~?

**Comment by davidpauljunior** [comment]
![y](https://user-images.githubusercontent.com/1489314/27583799-8fe1c98a-5b2d-11e7-98a6-6fedc1b227a5.png)

**Comment by davidpauljunior** [comment]
I'm not sure I'd instinctively think about graded browser support and progressive enhancement as being under the umbrella of 'performance'.

**Comment by hollsk** [comment]
Yeah, i had the same thought @davidpauljunior - but I couldn't think of anything more appropriate. 

* They don't belong in `markup` or `accessibility` 
* Both are distinct (& related) technical approaches, but they're not really `architecture`, exactly

Can you think of a category they could be contained by?

**Comment by jpw** [comment]
general concencus here to leave everything in the root unless > 1 related thing, then folder

don't know if this answers the question lol

**Comment by hollsk** [comment]
As per catchup:

* everyone agrees that GBS and PE don't strictly belong in performance
* we agreed that it's fine to leave pages uncategorised if there's no logical grouping
* general decision made to leave everything in the root unless > 1 related thing, then folder
