### ISSUE TITLE
I was serious when I mentioned discussing "frontend" & "front-end"

### ISSUE THREAD

**Issue by hollsk** [springernature/frontend-playbook#188]
I'm not convinced that there is a worthwhile reason for using two different formats to refer to things that are front-end related. 

**Pros and cons of using 2 different formats in particular circumstances:**

Pros:
* erm

Cons:
* People have to stop and think about which one to use
* People have to stop and think about whether the one used in a PR is correct or not
* It's something that needs to be _looked up_

--------------------------------------------------------

I don't really know how we got into this situation in the first place. Was it my fault? I hope it wasn't my fault. 

**Proposal:**

Use "frontend" for everything. I'll update the Playbook. Nobody speaks  or thinks about it ever again.

Pros:
* Everyone knows what to use
* It's still grammatically correct
* We will never need to speak of this or think about it ever again

Cons:
* People might not immediately find the content they're looking for if they search for "front-end" ¯\_(ツ)_/¯

**Comment by hollsk** [comment]
#96  (hollsk opened this issue on 6 Oct 2016)

😂

**Comment by andrewmee** [comment]
I don't think this is a problem
