### ISSUE TITLE
Tried to contribute but cannot gain access rights

### ISSUE THREAD

**Issue by ambrwlsn** [springernature/frontend-playbook#216]
![screen shot 2018-03-13 at 16 35 47](https://user-images.githubusercontent.com/20335874/37352025-9d07ae06-26dc-11e8-88d4-d543ac5de0fe.png)

**Comment by hollsk** [comment]
hello @ambrwlsn 👋thanks for contributing! 

Could you run me through what you're trying to do when you get the error message? Are you trying to push to the repo or clone it, or something else?

**Comment by ambrwlsn** [comment]
Hey! I cloned the repo, created a branch, made changes on the branch, committed, and then tried to push the branch up.

**Comment by hollsk** [comment]
Hm, that's what I thought should work, but seems not. Could you try forking the repo instead of cloning it and then raising your pull request from there? 

If that works then I'll update the README to recommend it 😄

**Comment by hollsk** [comment]
Thanks so much, @ambrwlsn !

**Comment by jpw** [comment]
Thanks @ambrwlsn ! :)
