### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by alexkilgour** [springernature/frontend-playbook#45]
At the moment we mention stylelint in the CSS documentation. I added an example config file for this, but think that we also use [SCSS lint](https://github.com/brigade/scss-lint), which I decided against using because of the Ruby dependency, and there is also [SASS lint](https://github.com/sasstools/sass-lint).

We also have Javascript linting in the nature playbook, should this be incorporated into the springernature one?

Is it wise to standardise around the same methods or do we just include details of all the methods used across teams? At the moment the section in CSS on 'the rules' only really matches the nature stuff and springerlink (because i nicked it).

Perhaps it would be better to have 'the rules' sitting within each language file, then a section on linting, which has methods for incorporating those rules?

**Comment by howlingmad** [comment]
It seems that sass-lint has sass/scss specific rules, and some generic CSS rules, but not as many as Stylelint.

My recommendation would be to use stylelint for linting the output CSS, and use sass-lint for linting using rules specific to to SASS.

**Comment by howlingmad** [comment]
We had some discussions in the catchup around:
- having a base set of rules that everyone gets, this is then extended on per project
- storing the default config in NPM so projects can require it
  - we could then version the config
  - auto generate documentation PR in frontend on every new version??

**Comment by hollsk** [comment]
@alexkilgour - linting for css, js, and dustjs is mentioned in the playbook now. Can we assume this ticket is complete?

**Comment by hollsk** [comment]
Oh, the ticket isn't complete because we don't have anything on SASS linting, which was the main point of you opening this. Joy, a conversation about SASS linting hoves itself over the horizon 🎉

**Comment by joseluisbolos** [comment]
Is this still needed?

**Comment by hollsk** [comment]
yes, unless alex decides no

**Comment by umaar** [comment]
On oscar we use https://github.com/sasstools/sass-lint which I would recommend

**Comment by danyalaytekin** [comment]
Any progress on this?

**Comment by umaar** [comment]
@alexkilgour, shall we close this based on https://github.com/springernature/frontend-playbook/commit/cd0343b51b5bb78b041b8e3cd13fe5cebc601203 ?

**Comment by alexkilgour** [comment]
Yes, this covers it. Thanks @umaar 👍
