### ISSUE TITLE
Defining dependency versions

### ISSUE THREAD

**Issue by andrewmee** [springernature/frontend-playbook#66]
It's probably a fairly minor point but I think it might be worth having a standard practice we use when defining dependency versions (for NPM-managed packages for example).

At the moment there are a range of ways that we specify versions - some are locked down to a particular release e.g. `1.2.3`, others to ranges of releases.  It could be useful to offer guidance on when it's preferably to use a range, and when it's better to lock to a specific version.

There are also several ways to define a range, which can cause confusion.  See https://github.com/npm/node-semver#advanced-range-syntax for a whole heap of examples.  I think we should aim to use the same range methods across the board (when they're equivalent and interchangeable).

**Comment by andrewmee** [comment]
FWIW I favour being as permissive with range as possible, so if it's a dependency that uses semver correctly it should be safe to allow patch release updates automatically.  And I prefer tilde range specifications e.g. `~1.2`

**Comment by hollsk** [comment]
Jose, is this issue ok to close?

**Comment by joseluisbolos** [comment]
Yup, this was added to the Playbook in #139
